# Generated by Django 2.0.4 on 2018-04-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenname', models.CharField(max_length=64)),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('follows', models.ManyToManyField(related_name='following', to='logic.Profile')),
                ('likes', models.ManyToManyField(related_name='liked_kweets', to='logic.Kweet')),
            ],
        ),
        migrations.AddField(
            model_name='kweet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Profile'),
        ),
    ]
