# Generated by Django 2.0.4 on 2018-04-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20180416_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kweet',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kweets', to='logic.Profile'),
        ),
    ]
