# Generated by Django 2.0.4 on 2018-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20180416_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_kweets',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='logic.Kweet'),
        ),
    ]
